export const siteConfig = {
  name: "Abhay Pratap Singh",
  title: "Senior Backend Engineer & Team Lead",
  description:
    "Abhay Pratap Singh is a Senior Backend Engineer and Team Lead specializing in scalable multi-tenant SaaS platforms and AI-powered backend systems. 5+ years of experience with Node.js, NestJS, Laravel, and PostgreSQL.",
  url: "https://abhaypratapsingh.co.in",
  linkedin: "https://www.linkedin.com/in/abhay-pratap-singhh/",
  github: "https://github.com/abhaysingh4feb-s",
  email: "abhaysingh4feb@gmail.com",
  location: "India",
  ogImage: "/opengraph-image",
  keywords: [
    "Abhay Pratap Singh",
    "Senior Backend Engineer",
    "Team Lead",
    "Backend Developer India",
    "NestJS Developer",
    "Laravel Developer",
    "Node.js Backend Engineer",
    "TypeScript Developer",
    "PostgreSQL Expert",
    "Multi-Tenant SaaS",
    "AI Systems Engineer",
    "pgvector",
    "LLM Pipeline",
    "SaaS Architect",
    "PHP Developer",
    "Voyantt Consultancy",
  ],
};
